### ISSUE TITLE
Nice! Why not use SCAN instead of KEYS *

### ISSUE THREAD

**Issue by FGRibreau** [maiha/redis-tsv.cr#1]
Good job @maiha it's not everyday we see a tool for Redis in crystal :)

I see that you used KEYS *, I'm sure you know [the performance implications][http://redis.io/commands/keys) in production, [SCAN](http://redis.io/commands/SCAN) would be a better alternative :)

Either way, redis-tsv will be shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [projet here](http://redisweekly.com/archive/141.html) :)

**Comment by maiha** [comment]
@FGRibreau Thanks for you advice!
To be honest, I'm newbie for redis commands :)
I'll fix `export` command to use SCAN one soon.
Thanks again!

**Comment by maiha** [comment]
Supported SCAN! Thanks!
